BASE = ../..

TARGET = host

PROGRAM = examples
SOURCES = examples.cc

LV_EXAMPLES = yes

include $(BASE)/gui/gui.mk
include $(BASE)/sdl/sdl.mk
include $(BASE)/logger/logger.mk
include $(BASE)/lib/lvgl/lvgl.mk
include $(BASE)/lib/json/json.mk
include $(BASE)/build/main.mk
