BASE = .

TARGET = host

PROGRAM = gui

SOURCES = main.cc logger.cc gui.cc
SOURCES += img/logo.c

include $(BASE)/sdl/sdl.mk
include $(BASE)/lib/lvgl/lvgl.mk
include $(BASE)/lib/json/json.mk
include $(BASE)/build/main.mk
