BASE = ../..

TARGET = host

PROGRAM = app
SOURCES = app.cc img/logo.c

include $(BASE)/gui/gui.mk
include $(BASE)/sdl/sdl.mk
include $(BASE)/logger/logger.mk
include $(BASE)/lib/lvgl/lvgl.mk
include $(BASE)/lib/json/json.mk
include $(BASE)/build/main.mk
